FROM kindest/node:v1.29.2

ENV DEBIAN_FRONTEND=noninteractive
ENV KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER=''
ENV KUBECONFIG=/etc/kubernetes/admin.conf

# Install ping, needed by Containernet
RUN apt update -yq && apt install -yy -qq iputils-ping net-tools iproute2

LABEL io.x-k8s.kind.role="control-plane"
LABEL io.x-k8s.kind.cluster="cl"

WORKDIR /

RUN mkdir -p /results/logs

ADD ./scripts/startcp.sh /kind
ADD ./scripts/copyconfigs.sh /kind
RUN touch /kind/kubeadm.conf

CMD [ "/bin/bash" ]