FROM kindest/node:v1.29.2

ENV DEBIAN_FRONTEND=noninteractive

# Install ping, needed by Containernet
RUN apt update -yq && apt install -yy -qq iputils-ping net-tools iproute2 tcpdump

LABEL io.x-k8s.kind.role="worker"
LABEL io.x-k8s.kind.cluster="cl"

WORKDIR /

RUN mkdir -p /results/logs
RUN mkdir -p /archives

RUN touch /kind/kubeadm.conf
ADD ./podfiles/archives /archives
ADD ./scripts/loadimages.sh /archives

CMD [ "/bin/bash" ]