FROM kindest/node:v1.29.2

ENV DEBIAN_FRONTEND=noninteractive

# Install ping, needed by Containernet
RUN apt update -yq && apt install -yy -qq iputils-ping net-tools iproute2

LABEL io.x-k8s.kind.role="worker"
LABEL io.x-k8s.kind.cluster="cl"

WORKDIR /

RUN touch /kind/kubeadm.conf

CMD [ "/bin/bash" ]