FROM alpine:latest
  
RUN apk add --update --no-cache \
        bash \
        tcpdump \
        iperf \
        busybox-extras \
        iproute2 \
        iputils

RUN mkdir -p /logs

CMD [ "ping", "10.0.0.1" ]