FROM alpine:latest
  
RUN apk add --update --no-cache \
        bash \
        tcpdump \
        iperf \
        busybox-extras \
        iproute2 \
        iputils

RUN mkdir -p /logs
RUN echo "export EGG=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/' | tr -d '.')" > cmd.sh
RUN echo 'ping -s 120 -p "$EGG" 10.0.0.1' >> cmd.sh

CMD [ "bash", "cmd.sh" ]